### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by GitHubGoody** [dcmeglio/homeassistant-keurig#1]
When I try to configure this on the Integrations page, the "Please wait, starting configuration wizard for Keurig Connect" message pops up, but never completes.

Eventually, it stops and issues this "Error Config flow could not be loaded: Unknown error"

I added this as a custom repo in HACS, downloaded, restarted HA, and tried to add it.

**Comment by GitHubGoody** [comment]
It seems to have worked. Thanks for developing it!

**Comment by dcmeglio** [comment]
Glad it's working! It was working flawlessly for me for the last 2-3 months but then broke yesterday when Keurig changed something. Hopefully they don't mess with it too much! 

None of Keurig's API is documented, so I can't really tell you what "all" the states are, just the states I've encountered so far. I do come across new states from time to time and I add them as I see them. Here are the states I know of with descriptions where it's not obvious:
* ready - Ready to brew, does not necessarily mean there is a pod though since you can brew hot water without a pod
* no water - Low/no water, will not brew unless you add water
* pod not removed - There is a pod in the brewer, but it's used already
* lid open
* canceling - You've cancelled an in progress brew
* brewing
* complete - Doesn't seem to consistently occur after a brewing but I've seen it sometimes. Usually the brew goes straight from brewing -> pod not removed

Pod statuses:
* empty - No pod loaded
* used - There is a pod, but it's already used
* present - A ready to use pod is loaded
* bad image - The sensor couldn't get a clear image of the pod, I think this means it knows there's a pod in there, it just has no clue what it is (I just discovered this status last night)
